# Generated by Django 4.2.14 on 2024-08-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=256, null=True)),
                ('agency_type', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('full_name', models.CharField(blank=True, max_length=512, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='internal_repr.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyContactJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyContactRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveFeatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EyeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigatingAgencyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=256, null=True)),
                ('date_reported', models.CharField(blank=True, max_length=256, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='internal_repr.agency')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='internal_repr.agencycontact')),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='internal_repr.city')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='internal_repr.county')),
            ],
        ),
        migrations.CreateModel(
            name='MissingFromTribalLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryResidenceOnTribalLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(blank=True, max_length=256, null=True)),
                ('nicknames', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRelatedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TribalAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('tag_expiration_year', models.IntegerField(blank=True, null=True)),
                ('tag_number', models.CharField(blank=True, max_length=256, null=True)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=256, null=True)),
                ('subject_related_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_info', to='internal_repr.subjectrelateditems')),
                ('tag_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='internal_repr.state')),
                ('vehicle_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='internal_repr.vehiclecolor')),
                ('vehicle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='internal_repr.vehiclemodel')),
                ('vehicle_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='internal_repr.vehiclestyle')),
            ],
        ),
        migrations.CreateModel(
            name='TribalAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enrolled', models.BooleanField(blank=True, null=True)),
                ('tribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='internal_repr.tribe')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_hair_description', models.CharField(blank=True, max_length=512, null=True)),
                ('body_hair_description', models.CharField(blank=True, max_length=512, null=True)),
                ('facial_hair_description', models.CharField(blank=True, max_length=512, null=True)),
                ('eye_description', models.CharField(blank=True, max_length=512, null=True)),
                ('hair_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_descriptions', to='internal_repr.haircolor')),
                ('left_eye_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_left_eye_descriptions', to='internal_repr.eyecolor')),
                ('right_eye_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_right_eye_descriptions', to='internal_repr.eyecolor')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_min_age', models.FloatField(blank=True, null=True)),
                ('current_max_age', models.FloatField(blank=True, null=True)),
                ('missing_min_age', models.FloatField(blank=True, null=True)),
                ('missing_max_age', models.FloatField(blank=True, null=True)),
                ('height_from_inches', models.FloatField(blank=True, null=True)),
                ('height_to_inches', models.FloatField(blank=True, null=True)),
                ('weight_from_lbs', models.FloatField(blank=True, null=True)),
                ('weight_to_lbs', models.FloatField(blank=True, null=True)),
                ('ethnicities', models.ManyToManyField(blank=True, related_name='subject_demographics_mixed', to='internal_repr.ethnicity')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_descriptions', to='internal_repr.gender')),
                ('primary_ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_demographics_primary', to='internal_repr.ethnicity')),
                ('tribal_affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_demographics', to='internal_repr.tribalaffiliation')),
                ('tribal_associations', models.ManyToManyField(related_name='subject_demographics', to='internal_repr.tribalassociation')),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='internal_repr.location')),
            ],
        ),
        migrations.CreateModel(
            name='MPCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, choices=[('Missing Persons Case', 'Mp'), ('Unidentified Body Case', 'Uid')], default='Missing Persons Case', editable=False, max_length=64, null=True)),
                ('namus_id', models.CharField(max_length=256)),
                ('namus_id_formatted', models.CharField(max_length=256)),
                ('ncmec_number', models.CharField(blank=True, max_length=256, null=True)),
                ('source_link', models.CharField(blank=True, max_length=2048, null=True)),
                ('internal_created', models.DateField(auto_now=True)),
                ('case_created', models.DateField()),
                ('case_last_modified', models.DateField()),
                ('circumstances_of_disappearance', models.TextField(blank=True, max_length=10000, null=True)),
                ('is_resolved', models.BooleanField(blank=True, null=True)),
                ('demographics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='internal_repr.subjectdemographics')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='internal_repr.subjectdescription')),
                ('identification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='internal_repr.subjectidentification')),
                ('last_known_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='internal_repr.sighting')),
                ('missing_from_tribal_land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='internal_repr.missingfromtriballand')),
                ('primary_investigating_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_primary', to='internal_repr.investigatingagencydata')),
                ('primary_residence_on_tribal_land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='internal_repr.primaryresidenceontriballand')),
                ('related_items', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='internal_repr.subjectrelateditems')),
                ('secondary_investigating_agencies', models.ManyToManyField(blank=True, related_name='cases_secondary', to='internal_repr.investigatingagencydata')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='internal_repr.state'),
        ),
        migrations.CreateModel(
            name='DescriptiveItemArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='internal_repr.descriptiveitemcategory')),
                ('subject_related_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_and_accessories', to='internal_repr.subjectrelateditems')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveFeatureArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='internal_repr.descriptivefeaturecategory')),
                ('subject_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distinctive_physical_features', to='internal_repr.subjectdescription')),
            ],
        ),
        migrations.AddField(
            model_name='agencycontact',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='internal_repr.agencycontactjobtitle'),
        ),
        migrations.AddField(
            model_name='agencycontact',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='internal_repr.agencycontactrole'),
        ),
        migrations.AddField(
            model_name='agency',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='internal_repr.location'),
        ),
    ]
