# Generated by Django 4.2.14 on 2024-08-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uidcase',
            name='details_of_recovery',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='uid_case', to='internal_repr.detailsofrecovery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uidcase',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_cases', to='internal_repr.uidstatus'),
        ),
    ]
