# Generated by Django 4.2.14 on 2024-08-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('source_type', models.CharField(blank=True, choices=[('Government Backed', 'Gov Backed'), ('Private', 'Private')], max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mpcase',
            name='primary_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_primary', to='internal_repr.source'),
        ),
        migrations.AddField(
            model_name='mpcase',
            name='secondary_sources',
            field=models.ManyToManyField(related_name='cases_secondary', to='internal_repr.source'),
        ),
    ]
