# Generated by Django 4.2.14 on 2024-08-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MPSubjectDescription',
            new_name='SubjectDescription',
        ),
        migrations.RenameField(
            model_name='uidsubjectidentification',
            old_name='nicknames',
            new_name='possible_nicknames',
        ),
        migrations.RemoveField(
            model_name='uidsubjectdemographics',
            name='status',
        ),
        migrations.AddField(
            model_name='detailsofrecovery',
            name='condition_of_remains',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_details', to='internal_repr.conditionofremains'),
        ),
        migrations.AddField(
            model_name='uidcase',
            name='description',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='uid_case', to='internal_repr.subjectdescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uidcase',
            name='details_of_recovery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_case', to='internal_repr.location'),
        ),
        migrations.AddField(
            model_name='uidcase',
            name='related_items',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='uid_case', to='internal_repr.subjectrelateditems'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uidcase',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uid_cases', to='internal_repr.uidstatus'),
        ),
        migrations.AlterField(
            model_name='uidcase',
            name='location_found',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_cases', to='internal_repr.location'),
        ),
    ]
