# Generated by Django 4.2.14 on 2024-08-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0002_rename_mpsubjectdescription_subjectdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uidsubjectidentification',
            name='possible_first_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='uidsubjectidentification',
            name='possible_last_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
