# Generated by Django 4.2.14 on 2024-08-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0002_source_mpcase_primary_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpcase',
            name='case_id',
            field=models.CharField(blank=True, default='MP0', editable=False, max_length=64, null=True),
        ),
    ]
