# Generated by Django 4.2.14 on 2024-08-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0002_alter_uidcase_details_of_recovery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpcase',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='uidcase',
            name='is_archived',
        ),
        migrations.AlterField(
            model_name='uidcase',
            name='location_found',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uid_cases', to='internal_repr.location'),
        ),
        migrations.AlterField(
            model_name='uidcase',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uid_cases', to='internal_repr.uidstatus'),
        ),
        migrations.CreateModel(
            name='CaseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_cases', models.ManyToManyField(to='internal_repr.mpcase')),
                ('uid_cases', models.ManyToManyField(to='internal_repr.uidcase')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_cases', models.ManyToManyField(to='internal_repr.mpcase')),
                ('uid_cases', models.ManyToManyField(to='internal_repr.uidcase')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_cases', models.ManyToManyField(to='internal_repr.mpcase')),
                ('uid_cases', models.ManyToManyField(to='internal_repr.uidcase')),
            ],
        ),
    ]
