# Generated by Django 4.2.14 on 2024-08-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0003_mpcase_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpcase',
            name='case_id',
            field=models.CharField(blank=True, default='MP0', max_length=64, null=True),
        ),
    ]
