# Generated by Django 4.2.14 on 2024-08-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0003_remove_mpcase_is_archived_remove_uidcase_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecases',
            name='mp_cases',
            field=models.ManyToManyField(related_name='active_storage', to='internal_repr.mpcase'),
        ),
        migrations.AlterField(
            model_name='activecases',
            name='uid_cases',
            field=models.ManyToManyField(related_name='active_storage', to='internal_repr.uidcase'),
        ),
        migrations.AlterField(
            model_name='archivedcases',
            name='mp_cases',
            field=models.ManyToManyField(related_name='archive_storage', to='internal_repr.mpcase'),
        ),
        migrations.AlterField(
            model_name='archivedcases',
            name='uid_cases',
            field=models.ManyToManyField(related_name='archive_storage', to='internal_repr.uidcase'),
        ),
    ]
