# Generated by Django 4.2.14 on 2024-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0004_alter_mpcase_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
