# Generated by Django 4.2.14 on 2024-08-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0004_uidcase_demographics_uidcase_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uidcase',
            name='date_found',
            field=models.CharField(max_length=256),
        ),
    ]
