# Generated by Django 4.2.14 on 2024-08-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0005_location_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpcase',
            name='source_link',
        ),
        migrations.AddField(
            model_name='mpcase',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='case_id',
            field=models.CharField(blank=True, default='C_MP0', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='CaseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=4096)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cases', to='internal_repr.source')),
            ],
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='primary_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cases_primary', to='internal_repr.casesource'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='secondary_sources',
            field=models.ManyToManyField(related_name='cases_secondary', to='internal_repr.casesource'),
        ),
    ]
