# Generated by Django 4.2.14 on 2024-08-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0006_remove_mpcase_source_link_mpcase_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_href', models.CharField(max_length=4096)),
                ('thumbnail_href', models.CharField(max_length=4096)),
                ('file_path', models.CharField(blank=True, default='-', max_length=512)),
                ('height_poster', models.IntegerField(blank=True, null=True)),
                ('width_poster', models.IntegerField(blank=True, null=True)),
                ('height_thumbnail', models.IntegerField(blank=True, null=True)),
                ('width_thumbnail', models.IntegerField(blank=True, null=True)),
                ('download_link', models.CharField(blank=True, max_length=4096, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_images_default', to='internal_repr.image')),
                ('other_images', models.ManyToManyField(related_name='case_images_other', to='internal_repr.image')),
            ],
        ),
        migrations.AddField(
            model_name='mpcase',
            name='images',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='internal_repr.caseimages'),
            preserve_default=False,
        ),
    ]
