# Generated by Django 4.2.14 on 2024-08-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0007_image_caseimages_mpcase_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpcase',
            old_name='images',
            new_name='case_images',
        ),
        migrations.RenameField(
            model_name='mpcase',
            old_name='internal_created',
            new_name='case_internal_created',
        ),
    ]
