# Generated by Django 4.2.14 on 2024-08-06 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0008_rename_images_mpcase_case_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencycontact',
            name='first_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencycontact',
            name='full_name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencycontact',
            name='last_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencycontactjobtitle',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencycontactrole',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencytype',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseimages',
            name='default_image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='case_images_default', to='internal_repr.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descriptivefeaturecategory',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descriptiveitemcategory',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eyecolor',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='haircolor',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investigatingagencydata',
            name='agency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='internal_repr.agency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investigatingagencydata',
            name='contact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='internal_repr.agencycontact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investigatingagencydata',
            name='date_reported',
            field=models.DateField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missingfromtriballand',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='case_id',
            field=models.CharField(blank=True, default='C_MP0', max_length=64),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='case_type',
            field=models.CharField(blank=True, choices=[('Missing Persons Case', 'Mp'), ('Unidentified Body Case', 'Uid')], default='Missing Persons Case', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='circumstances_of_disappearance',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='is_resolved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='missing_from_tribal_land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='internal_repr.missingfromtriballand'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='ncmec_number',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='primary_investigating_agency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cases_primary', to='internal_repr.investigatingagencydata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='primary_residence_on_tribal_land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='internal_repr.primaryresidenceontriballand'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='secondary_investigating_agencies',
            field=models.ManyToManyField(related_name='cases_secondary', to='internal_repr.investigatingagencydata'),
        ),
        migrations.AlterField(
            model_name='primaryresidenceontriballand',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('Government Backed', 'Gov Backed'), ('Private', 'Private')], default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tribalaffiliation',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tribalassociation',
            name='is_enrolled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tribalassociation',
            name='tribe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='internal_repr.tribe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tribe',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclecolor',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclestyle',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
