# Generated by Django 4.2.14 on 2024-08-06 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0009_alter_agency_name_alter_agencycontact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigatingagencydata',
            name='case_number',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='investigatingagencydata',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='internal_repr.agencycontact'),
        ),
        migrations.AlterField(
            model_name='investigatingagencydata',
            name='date_reported',
            field=models.DateField(max_length=256, null=True),
        ),
    ]
