# Generated by Django 4.2.14 on 2024-08-07 02:52

from django.db import migrations, models
import django.db.models.deletion
import internal_repr.models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0010_alter_investigatingagencydata_case_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='jurisdiction',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='internal_repr.location'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='agencycontact',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='internal_repr.agency'),
        ),
        migrations.AlterField(
            model_name='agencycontact',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='internal_repr.agencycontactjobtitle'),
        ),
        migrations.AlterField(
            model_name='agencycontact',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='internal_repr.agencycontactrole'),
        ),
        migrations.AlterField(
            model_name='caseimages',
            name='default_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_images_default', to='internal_repr.image'),
        ),
        migrations.AlterField(
            model_name='casesource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_cases', to='internal_repr.source'),
        ),
        migrations.AlterField(
            model_name='descriptivefeaturearticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='internal_repr.descriptivefeaturecategory'),
        ),
        migrations.AlterField(
            model_name='descriptiveitemarticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='internal_repr.descriptiveitemcategory'),
        ),
        migrations.AlterField(
            model_name='image',
            name='download_link',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='height_poster',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='height_thumbnail',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width_poster',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width_thumbnail',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='investigatingagencydata',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='internal_repr.agency'),
        ),
        migrations.AlterField(
            model_name='investigatingagencydata',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='internal_repr.agencycontact'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='internal_repr.city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='internal_repr.county'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='internal_repr.state'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='case_images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='internal_repr.caseimages'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='case_type',
            field=models.CharField(blank=True, default=internal_repr.models.CaseType['MP'], editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='demographics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='internal_repr.subjectdemographics'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='internal_repr.subjectdescription'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='identification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='internal_repr.subjectidentification'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='last_known_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='internal_repr.sighting'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='missing_from_tribal_land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='internal_repr.missingfromtriballand'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='primary_investigating_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_primary', to='internal_repr.investigatingagencydata'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='primary_residence_on_tribal_land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='internal_repr.primaryresidenceontriballand'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='primary_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_primary', to='internal_repr.casesource'),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='related_items',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='internal_repr.subjectrelateditems'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sightings', to='internal_repr.location'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='current_max_age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='current_min_age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='ethnicities',
            field=models.ManyToManyField(related_name='subject_demographics_mixed', to='internal_repr.ethnicity'),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_descriptions', to='internal_repr.gender'),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='height_from_inches',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='height_to_inches',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='missing_max_age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='missing_min_age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='primary_ethnicity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_demographics_primary', to='internal_repr.ethnicity'),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='tribal_affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_demographics', to='internal_repr.tribalaffiliation'),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='weight_from_lbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='weight_to_lbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='body_hair_description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='eye_description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='facial_hair_description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='hair_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_descriptions', to='internal_repr.haircolor'),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='head_hair_description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='left_eye_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_left_eye_descriptions', to='internal_repr.eyecolor'),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='right_eye_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_right_eye_descriptions', to='internal_repr.eyecolor'),
        ),
        migrations.AlterField(
            model_name='subjectidentification',
            name='middle_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='subjectidentification',
            name='nicknames',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='tag_expiration_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='tag_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='internal_repr.state'),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='vehicle_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='internal_repr.vehiclecolor'),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='vehicle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='internal_repr.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='vehicle_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='internal_repr.vehiclestyle'),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='vehicle_year',
            field=models.IntegerField(null=True),
        ),
    ]
