# Generated by Django 4.2.14 on 2024-08-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0011_alter_agency_agency_type_alter_agency_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='internal_repr.location'),
        ),
        migrations.AlterField(
            model_name='agencycontact',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='internal_repr.agencycontactjobtitle'),
        ),
        migrations.AlterField(
            model_name='agencycontact',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='internal_repr.agencycontactrole'),
        ),
        migrations.AlterField(
            model_name='caseimages',
            name='default_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='case_images_default', to='internal_repr.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casesource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cases', to='internal_repr.source'),
        ),
        migrations.AlterField(
            model_name='descriptiveitemarticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='internal_repr.descriptiveitemcategory'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='internal_repr.city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='internal_repr.county'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='internal_repr.state'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='internal_repr.location'),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='tag_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='internal_repr.state'),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='vehicle_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='internal_repr.vehiclecolor'),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='vehicle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='internal_repr.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='vehicle_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='internal_repr.vehiclestyle'),
        ),
    ]
