# Generated by Django 4.2.14 on 2024-08-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_repr', '0012_alter_agency_location_alter_agencycontact_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpcase',
            name='case_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
