# Generated by Django 4.2.14 on 2024-08-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_tribe_remove_subjectidentification_current_max_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigatingagencydata',
            name='case_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='investigatingagencydata',
            name='date_reported',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
