# Generated by Django 4.2.14 on 2024-08-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0005_agencycontact_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='scrapers.state'),
        ),
    ]
