# Generated by Django 4.2.14 on 2024-08-01 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpcase',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mpcase',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='height_from_inches',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='height_to_inches',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='primary_ethnicity',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='tribal_affiliation',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='weight_from_lbs',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='weight_to_lbs',
        ),
        migrations.AddField(
            model_name='mpcase',
            name='case_created',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpcase',
            name='case_last_modified',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpcase',
            name='internal_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mpcase',
            name='ncmec_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mpcase',
            name='source_link',
            field=models.CharField(default=None, max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='namus_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='namus_id_formatted',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='SubjectDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_from_inches', models.FloatField(blank=True, null=True)),
                ('height_to_inches', models.FloatField(blank=True, null=True)),
                ('weight_from_lbs', models.FloatField(blank=True, null=True)),
                ('weight_to_lbs', models.FloatField(blank=True, null=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_descriptions', to='scrapers.gender')),
                ('primary_ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_descriptions', to='scrapers.ethnicity')),
                ('tribal_affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_descriptions', to='scrapers.tribalaffiliation')),
            ],
        ),
        migrations.AddField(
            model_name='mpcase',
            name='demographics',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='scrapers.subjectdemographics'),
            preserve_default=False,
        ),
    ]
