# Generated by Django 4.2.14 on 2024-08-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_remove_mpcase_created_remove_mpcase_last_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjectidentification',
            name='current_max_age',
        ),
        migrations.RemoveField(
            model_name='subjectidentification',
            name='current_min_age',
        ),
        migrations.RemoveField(
            model_name='subjectidentification',
            name='missing_max_age',
        ),
        migrations.RemoveField(
            model_name='subjectidentification',
            name='missing_min_age',
        ),
        migrations.AddField(
            model_name='subjectdemographics',
            name='current_max_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectdemographics',
            name='current_min_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectdemographics',
            name='ethnicities',
            field=models.ManyToManyField(blank=True, related_name='subject_demographics_mixed', to='scrapers.ethnicity'),
        ),
        migrations.AddField(
            model_name='subjectdemographics',
            name='is_enrolled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectdemographics',
            name='missing_max_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectdemographics',
            name='missing_min_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='namus_id',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='namus_id_formatted',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpcase',
            name='secondary_investigating_agencies',
            field=models.ManyToManyField(blank=True, related_name='cases_secondary', to='scrapers.investigatingagencydata'),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='primary_ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_demographics_primary', to='scrapers.ethnicity'),
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='tribal_affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_demographics', to='scrapers.tribalaffiliation'),
        ),
        migrations.AddField(
            model_name='subjectdemographics',
            name='tribal_associations',
            field=models.ManyToManyField(blank=True, related_name='subject_demographics', to='scrapers.tribe'),
        ),
    ]
