# Generated by Django 4.2.14 on 2024-08-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0004_alter_investigatingagencydata_case_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencycontact',
            name='full_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
