# Generated by Django 4.2.14 on 2024-08-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0006_alter_location_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
