# Generated by Django 4.2.14 on 2024-08-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0007_alter_agency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpcase',
            name='source_link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
