# Generated by Django 4.2.14 on 2024-08-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0008_alter_mpcase_source_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectdemographics',
            name='is_enrolled',
        ),
        migrations.CreateModel(
            name='TribalAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enrolled', models.BooleanField(blank=True, null=True)),
                ('tribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='scrapers.tribe')),
            ],
        ),
        migrations.AlterField(
            model_name='subjectdemographics',
            name='tribal_associations',
            field=models.ManyToManyField(blank=True, related_name='subject_demographics', to='scrapers.tribalassociation'),
        ),
    ]
