# Generated by Django 4.2.14 on 2024-08-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0009_remove_subjectdemographics_is_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectdemographics',
            name='tribal_associations',
            field=models.ManyToManyField(related_name='subject_demographics', to='scrapers.tribalassociation'),
        ),
    ]
